#RANDOM MODULE
#askpython.com - Check this site for module help
import random

#THIS WILL PRINT ONE RANDOM NUMBER FROM 1-10 WHENEVER YOU RUN THIS CODE
random_integer = random.randint(1,10)
print(random_integer)

#FOR THE RANDOM FLOAT NUMBER
#0.0000000000-0.99999999999.......
random_float = random.random()
print(random_float)


#EXERCISE
#LOVE SCORE
love_score = random.randint(1,100)
print(f"Your love score is {love_score}")

#MODULE
#IF YOU WRITE A CODE, A LARGE PIECE OF CODE FROM TOP TO BOTTOM
#WE CAN'T ABLE TO UNDERSTAND ALL THE THINGS AND CLUMSY
#SO, WE ARE MAKING THEM AS SMALL PIECES AND EACH PIECE OF CODE RESPONSIBLE TO THEIR OWN FUNCTIONALITY
'''
EXAMPLE, IF YOU ARE MANUFACTURING A CAR
ONLY ONE PERSON WORKING ON ALL THE PARTS AND DESIGN MAKES CLUMSY AND TIME TAKING
IF EACH PERSON ALLOCATED TO DIFFERENT SECTIONS LIKE FOR WHEELS, CHASIS, ENGINE ETC..,
IT WOULD BE VERY EASY TO WORK AND PROGRESS
'''


#CREATING A OWN MODULE:
'''
NOW CREATE A FILE CALLED : "my-module.py"
ASSIGN A VARIABLE AND ITS VALUES LIKE : pi=3.14
NOW, WILL CALL THAT MODULE IN THIS FILE
'''
#IMPORT THE MODULE WITH THE FILE NAME
import my_module

#PRINT THE VARIABLE VALUE DECLARED IN THE my_module.py
print(my_module.pi)