'''
INDENTATIONS ARE SPACES WHICH TELLS THE PIECE OF CODE TO EXECUTE WITHIN THE FUNCTION OR LOOP
- USE TAB OR SPACES
- IF YOU USE SPACE, IT SHOULD BE 4 SPACES GAP
- YOU HAVE TO PROVIDE EQUAL INDENTATIONS IN NESTED BLOCKS
'''

#EXAMPLE
sky="Pink"
def my_function():
    print("Hello, world!")
    if (sky=="Blue"):
        print ("Hello, Blue")
        
        
'''
HERE IF YOU OBSERVE, THERE IS A SPACES AFTER THE FUNCTION DEFINITION LINE
IN IF BLOCK THERE ARE TWO TAB SPACES AFTER THE IF STATEMENT
THIS MEANS THAT INDENTED BLOCK WILL EXECUTE WITHIN THE SPECIFIED CONDITION OR FUNCTION
'''

#CALLING FUNCTION        
my_function()