#EXERCISE
'''
FIZZ-BUZZ-GAME
TAKE A RANGE IN BETWEEN 1-50:
IF THE NUMBER IS DIVISIBLE BY 3 : PRINT FIZZ
IF THE NUMBER IS DIVISIBLE BY 5 : PRINT BUZZ
IF THE NUMBER IS DIVISIBLE BY BOTH 3 AND 5 : PRINT FIZZBUZZ
EX: 1,2,FIZZ,4,BUZZ,FIZZ,.....11,FIZZ,13,14,FIZZBUZZ
'''
for i in range(1,51):
    if i%3 ==0 and i%5==0 :
    #NOTE: THIS IF STATEMENT EXECUTE FROM TOP TO BOTTOM
    #SO, ELSIF COMES ONLY WHEN IF STATEMENT IS FALSE OR NOT SATISFIED
    #HENCE, WE HAVE TO WRITE THIS CONDITION FIRST
        print("FizzBuzz")
    elif i%3 == 0:
        print("Fizz")
    elif i%5 ==0:
        print("Buzz")
    else:
        print(i)